### ISSUE TITLE
A.6.4.0400. - Draft Mode

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#29]
Feature: [A.6.4.0400. - Draft Mode](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/A/Project%20Setup_4/A.6.4.0400.%20-%20Draft%20Mode.feature)

**Comment by schatto1** [comment]
Currently failing due to "I add a new {fieldType} field labeled {string} with variable name {string}" step definition for Online Designer not able to find the draggable field containing the newly created variable.

v13 and v14.0 uses "Variable: ", but v14.5 onwards uses "Field Name: ". Will need to modify the following to be able to find either of those:
`cy.get('button').contains(save_button_text).click().then(() => {
            cy.get('table#draggable').should(($t) => {
                expect($t).to.contain('Variable: '+ variable_name)
            })`

[RCTF PR #10](https://github.com/aldefouw/rctf/pull/10) tried to address this but this feature test is still failing.

**Comment by mmcev106** [comment]
@schatto1, do you have ideas for how to resolve this?  We're all REALLY appreciating your collaboration, but feel free to pass things off to me if/when needed.

**Comment by aldefouw** [comment]
@mmcev106  & @schatto1 - I'm taking a peek at this in terms of RCTF.  

I think this might be related to REDCap adjustments to re-ordering the fields within the Online Designer.  If so, probably a trivial but important change to the selector within this step: `I add a new {fieldType} field labeled {string} with variable name {string}`

**Comment by schatto1** [comment]
@aldefouw $ @mmcev106 - I just created [RCTF PR #14](https://github.com/aldefouw/rctf/pull/14) to document what I tried and get a discussion going. I figured I'd put it there so you can push your commits/solutions to that branch

**Comment by aldefouw** [comment]
@mmcev106  - Issued a patch at v1.0.104 on RCTF.  

Should not be any Gherkin feature test changes required.  Just need to rerun the whole test suite at v1.0.104.

Let me know if any questions.

**Comment by mmcev106** [comment]
Passing!  Thanks very much @aldefouw & @schatto1!

![image](https://github.com/user-attachments/assets/dc16b417-1dfd-41b2-b10a-a2b409fce8b3)
